spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_flow_manager
    username: REMOVED_DB_USERNAME
    password: REMOVED_DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080