CREATE TABLE storage_locations (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   code VARCHAR(50) NOT NULL,
                                   zone VARCHAR(100) NOT NULL,
                                   description VARCHAR(255) NOT NULL,
                                   active BOOLEAN NOT NULL,
                                   CONSTRAINT uk_storage_locations_code UNIQUE (code)
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sku VARCHAR(255) NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          description TEXT,
                          unit VARCHAR(255) NOT NULL,
                          quantity INTEGER NOT NULL,
                          minimum_quantity INTEGER,
                          status VARCHAR(255) NOT NULL,
                          storage_location_id BIGINT,
                          CONSTRAINT uk_products_sku UNIQUE (sku),
                          CONSTRAINT fk_products_storage_location
                              FOREIGN KEY (storage_location_id)
                                  REFERENCES storage_locations (id)
);

CREATE TABLE stock_movements (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 product_id BIGINT NOT NULL,
                                 movement_type VARCHAR(20) NOT NULL,
                                 quantity INTEGER NOT NULL,
                                 resulting_quantity INTEGER NOT NULL,
                                 note VARCHAR(255),
                                 movement_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                 CONSTRAINT fk_stock_movements_product
                                     FOREIGN KEY (product_id)
                                         REFERENCES products (id)
);